name: default

kind: pipeline
type: docker

steps:

- name: compile
  image: mhart/alpine-node
  commands:
    - npm install
  when:
    branch:
    - master

- name: push dockerhub  
  image: plugins/docker
  settings:
    repo: thomaslacaze/portfolio
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
      branch:
      - master

# - name: deploy
#   image: appleboy/drone-ssh
#   settings:
#     host: 
#        from_secret: ssh_host 
#     username: 
#         from_secret: ssh_username
#     password: 
#         from_secret: ssh_password
#     port: 
#         from_secret: ssh_port
#     script:
#       - docker pull thomaslacaze/portfolio
#       - cd /home/thomas/mailcow-dockerized && docker-compose up -d portfolio
#   when:
#     branch:
#     - master